---
driver:
  name: ec2
  aws_ssh_key_id: chef_demo_2x
  region: us-west-2
  security_group_ids: sg-0a11183f894170e06
  subnet_id: subnet-02e95c1cb4e77660c
  associate_public_ip: true
  instance_type: t2.micro
  tags:
    # Replace YOURNAME and YOURCOMPANY here
    Name: "Chef Training Node for <YOURNAME>, Rees"
    user: Administrator
    X-Contact: "Anthony Rees"
    X-Application: "APAC"
    X-Dept: "Sales"
    X-Customer: "Rees"
    X-Project: "BJC-Demo"
    X-Termination-Date: "2018-07-20T12:04:30Z"
    X-TTL: 4

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.12.3
  chef_license: accept
  
verifier:
  name: inspec
  format: documentation

platforms:
  - name: centos-7
    transport:
      username: centos
      ssh_key: C:\Users\Chef\.ssh\id_rsa
    driver_config:
      user_data: C:/Users/chef/user_data

suites:
  - name: default
    run_list:
      - recipe[bjc_linux_bootstrap::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
